name: pixlet

on:
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.16.12"

      - name: Install buildifier
        run: make install-buildifier

      - name: Run buildifier
        run: buildifier -d -r ./

  build-and-test:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.16.12"

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo ./scripts/setup-linux.sh

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install webp

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Build
        run: make build

      - name: Set pixlet version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Build Release Linux
        if: matrix.os == 'ubuntu-latest'
        run: make release-linux
        env:
          PIXLET_VERSION: ${{ steps.vars.outputs.tag }}

      - name: Test
        run: make test

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: build
